

CREATE SEQUENCE audit_log_seq START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE TABLE CUSTOMERS (
    customer_id NUMBER PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    national_id VARCHAR2(20) UNIQUE NOT NULL,
    risk_level VARCHAR2(10) CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE ACCOUNTS (
    account_id NUMBER PRIMARY KEY,
    customer_id NUMBER REFERENCES CUSTOMERS(customer_id),
    account_status VARCHAR2(10) CHECK (account_status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE TABLE STAFF (
    staff_id NUMBER PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    full_name VARCHAR2(100),
    job_role VARCHAR2(50)
);

CREATE TABLE AUDIT_LOGS (
    log_id NUMBER PRIMARY KEY,
    event_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    db_user VARCHAR2(50),
    action_type VARCHAR2(50),
    table_affected VARCHAR2(50),
    action_details VARCHAR2(4000)
);


CREATE ROLE BANK_ADMIN_ROLE;
CREATE ROLE BANK_OFFICER_ROLE;
CREATE ROLE AUDITOR_ROLE;

CREATE PROFILE STAFF_PROFILE LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    SESSIONS_PER_USER 2;

CREATE PROFILE CUSTOMER_PROFILE LIMIT
    FAILED_LOGIN_ATTEMPTS 5
    IDLE_TIME 15;
